In [20]:
import nltk
import pandas as pd
from nltk.tokenize import sent_tokenize,word_tokenize 
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords

regexptokenizer=RegexpTokenizer(r'\w+')

mytext = "In his left hand was a gold snuff box, from which, as he capered down the hill, cutting all manner of fantastic steps, he took snuff incessantly with an air of the greatest possible self satisfaction." 

#word_tokens=word_tokenize(mytext)

regexp_tokens= regexptokenizer.tokenize(mytext)

pure_tokens=[token.lower() for token in regexp_tokens if token.lower() not in stopwords.words('english')]

#OR 

for token in regexp_tokens:
    if token.lower() not in stopwords.words('english'):
        pure_tokens.append(token.lower())
        
        
word_tokens

from nltk.stem import PorterStemmer

stemmer=PorterStemmer()

stemmed_tokens=[]

for token in pure_tokens:
    stemmed_tokens.append(stemmer.stem(token))
    
stemmed_tokens

comparisons_df=pd.DataFrame({'Token':pure_tokens,'Stemmed_tokens':stemmed_tokens})


comparisons_df

#regexp_tokens

Token Stemmed_tokens
0           left           left
1           hand           hand
2           gold           gold
3          snuff          snuff
4            box            box
5        capered          caper
6           hill           hill
7        cutting            cut
8         manner         manner
9      fantastic        fantast
10         steps           step
11          took           took
12         snuff          snuff
13   incessantly    incessantli
14           air            air
15      greatest       greatest
16      possible        possibl
17          self           self
18  satisfaction      satisfact
19          left           left
20          hand           hand
21          gold           gold
22         snuff          snuff
23           box            box
24       capered          caper
25          hill           hill
26       cutting            cut
27        manner         manner
28     fantastic        fantast
29         steps           step
30          took           took
31         snuff          snuff
32   incessantly    incessantli
33           air            air
34      greatest       greatest
35      possible        possibl
36          self           self
37  satisfaction      satisfact

In [13]:
from nltk.stem import WordNetLemmatizer,PorterStemmer

lemmatizer=WordNetLemmatizer()

lemmatizer.lemmatize('cacti',pos='n')

'cactus'

In [14]:
stemmer=PorterStemmer()
stemmer.stem('cacti')

'cacti'

In [18]:
mytext = "In his left hand was a gold snuff box, from which, as he capered down the hill, cutting all manner of fantastic steps, he took snuff incessantly with an air of the greatest possible self satisfaction." 

regexp_tokens= regexptokenizer.tokenize(mytext)
regexp_tokens

pure_tokens=[token.lower() for token in regexp_tokens if token.lower() not in stopwords.words('english')]



In [4]:
from nltk.corpus import stopwords

stopwords.words('spanish')

['de',
 'la',
 'que',
 'el',
 'en',
 'y',
 'a',
 'los',
 'del',
 'se',
 'las',
 'por',
 'un',
 'para',
 'con',
 'no',
 'una',
 'su',
 'al',
 'lo',
 'como',
 'más',
 'pero',
 'sus',
 'le',
 'ya',
 'o',
 'este',
 'sí',
 'porque',
 'esta',
 'entre',
 'cuando',
 'muy',
 'sin',
 'sobre',
 'también',
 'me',
 'hasta',
 'hay',
 'donde',
 'quien',
 'desde',
 'todo',
 'nos',
 'durante',
 'todos',
 'uno',
 'les',
 'ni',
 'contra',
 'otros',
 'ese',
 'eso',
 'ante',
 'ellos',
 'e',
 'esto',
 'mí',
 'antes',
 'algunos',
 'qué',
 'unos',
 'yo',
 'otro',
 'otras',
 'otra',
 'él',
 'tanto',
 'esa',
 'estos',
 'mucho',
 'quienes',
 'nada',
 'muchos',
 'cual',
 'poco',
 'ella',
 'estar',
 'estas',
 'algunas',
 'algo',
 'nosotros',
 'mi',
 'mis',
 'tú',
 'te',
 'ti',
 'tu',
 'tus',
 'ellas',
 'nosotras',
 'vosostros',
 'vosostras',
 'os',
 'mío',
 'mía',
 'míos',
 'mías',
 'tuyo',
 'tuya',
 'tuyos',
 'tuyas',
 'suyo',
 'suya',
 'suyos',
 'suyas',
 'nuestro',
 'nuestra',
 'nuestros',
 'nuestras',
 'vuestr

In [8]:
mytext = "In his left hand was a gold snuff box, from which, as he capered down the hill, cutting all manner of fantastic steps, he took snuff incessantly with an air of the greatest possible self satisfaction." 

word_tokens=word_tokenize(mytext)

regexp_tokens=regexptokenizer.tokenize(mytext)

pure_tokens=[token.lower() for token in regexp_tokens if token.lower() not in stopwords.words('english')]

pure_tokens



['left',
 'hand',
 'gold',
 'snuff',
 'box',
 'capered',
 'hill',
 'cutting',
 'manner',
 'fantastic',
 'steps',
 'took',
 'snuff',
 'incessantly',
 'air',
 'greatest',
 'possible',
 'self',
 'satisfaction']

In [23]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer



final_tokens=[word.lower() for word in mytext.split() if word.lower() not in stopwords.words('english')]

final_tokens

snowballstemmer=SnowballStemmer('english')

snowstemmed_tokens=[snowballstemmer.stem(token) for token in final_tokens]

#pos_tags= nltk.pos_tag(final_tokens)

snowstemmed_tokens



['left',
 'hand',
 'gold',
 'snuff',
 'box,',
 'which,',
 'caper',
 'hill,',
 'cut',
 'manner',
 'fantast',
 'steps,',
 'took',
 'snuff',
 'incess',
 'air',
 'greatest',
 'possibl',
 'self',
 'satisfaction.']

In [28]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer() 
print(stemmer.stem('working'))

from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
lemmatized_tokens=[lemmatizer.lemmatize(token) for token in pure_tokens]
lemmatized_tokens

work


['left',
 'hand',
 'gold',
 'snuff',
 'box',
 'capered',
 'hill',
 'cutting',
 'manner',
 'fantastic',
 'step',
 'took',
 'snuff',
 'incessantly',
 'air',
 'greatest',
 'possible',
 'self',
 'satisfaction',
 'left',
 'hand',
 'gold',
 'snuff',
 'box',
 'capered',
 'hill',
 'cutting',
 'manner',
 'fantastic',
 'step',
 'took',
 'snuff',
 'incessantly',
 'air',
 'greatest',
 'possible',
 'self',
 'satisfaction']

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
>>> corpus = [
...     'This is the first document.',
...     'This document is the second document.',
...     'And this is the third one.',
...     'Is this the first document?',
... ]
>>> vectorizer = TfidfVectorizer()
>>> X = vectorizer.fit_transform(corpus)
>>> print(vectorizer.get_feature_names())
['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
>>> print(X.shape)
(4, 9)

X

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
(4, 9)


<4x9 sparse matrix of type '<class 'numpy.float64'>'
	with 21 stored elements in Compressed Sparse Row format>

In [1]:
from nltk.corpus import wordnet as wn

#print(wn.synsets('grow'))


synonyms = []
antonyms = []

for syn in wn.synsets("active"):
    for l in syn.lemmas():
        synonyms.append(l.name())
        if l.antonyms():
            antonyms.append(l.antonyms()[0].name())

print(set(synonyms))
print(set(antonyms))

syn.lemmas()

{'participating', 'dynamic', 'active_voice', 'combat-ready', 'active_agent', 'fighting', 'alive', 'active'}
{'stative', 'dormant', 'quiet', 'inactive', 'extinct', 'passive', 'passive_voice'}


[Lemma('active.a.14.active')]

In [7]:
wn.synsets("playing")

[Synset('playing.n.01'),
 Synset('playing.n.02'),
 Synset('acting.n.01'),
 Synset('play.v.01'),
 Synset('play.v.02'),
 Synset('play.v.03'),
 Synset('act.v.03'),
 Synset('play.v.05'),
 Synset('play.v.06'),
 Synset('play.v.07'),
 Synset('act.v.05'),
 Synset('play.v.09'),
 Synset('play.v.10'),
 Synset('play.v.11'),
 Synset('play.v.12'),
 Synset('play.v.13'),
 Synset('play.v.14'),
 Synset('play.v.15'),
 Synset('play.v.16'),
 Synset('play.v.17'),
 Synset('play.v.18'),
 Synset('toy.v.02'),
 Synset('play.v.20'),
 Synset('dally.v.04'),
 Synset('play.v.22'),
 Synset('dally.v.01'),
 Synset('play.v.24'),
 Synset('act.v.10'),
 Synset('play.v.26'),
 Synset('bring.v.03'),
 Synset('play.v.28'),
 Synset('play.v.29'),
 Synset('bet.v.02'),
 Synset('play.v.31'),
 Synset('play.v.32'),
 Synset('play.v.33'),
 Synset('meet.v.10'),
 Synset('play.v.35')]

In [8]:
wn.synsets('good')

[Synset('good.n.01'),
 Synset('good.n.02'),
 Synset('good.n.03'),
 Synset('commodity.n.01'),
 Synset('good.a.01'),
 Synset('full.s.06'),
 Synset('good.a.03'),
 Synset('estimable.s.02'),
 Synset('beneficial.s.01'),
 Synset('good.s.06'),
 Synset('good.s.07'),
 Synset('adept.s.01'),
 Synset('good.s.09'),
 Synset('dear.s.02'),
 Synset('dependable.s.04'),
 Synset('good.s.12'),
 Synset('good.s.13'),
 Synset('effective.s.04'),
 Synset('good.s.15'),
 Synset('good.s.16'),
 Synset('good.s.17'),
 Synset('good.s.18'),
 Synset('good.s.19'),
 Synset('good.s.20'),
 Synset('good.s.21'),
 Synset('well.r.01'),
 Synset('thoroughly.r.02')]

# Topic Modelling

In [5]:
# Topic Modelling

doc1 = "Sugar is bad to consume. My sister likes to have sugar, but not my father."
doc2 = "My father spends a lot of time driving my sister around to dance practice."
doc3 = "Doctors suggest that driving may cause increased stress and blood pressure."
doc4 = "Sometimes I feel pressure to perform well at school, but my father never seems to drive my sister to do better."
doc5 = "Health experts say that Sugar is not good for your lifestyle."

doc_complete = [doc1, doc2, doc3, doc4, doc5]

from nltk.corpus import stopwords 
from nltk.stem.wordnet import WordNetLemmatizer
import string
stop = set(stopwords.words('english'))
exclude = set(string.punctuation) 
lemma = WordNetLemmatizer()

#dictionary = corpora.Dictionary(doc_clean)

def clean(doc):
    stop_free = " ".join([i for i in doc.lower().split() if i not in stop])
    punc_free = ''.join(ch for ch in stop_free if ch not in exclude)
    normalized = " ".join(lemma.lemmatize(word) for word in punc_free.split())
    return normalized

doc_clean = [clean(doc).split() for doc in doc_complete]        


import gensim
from gensim import corpora

dictionary = corpora.Dictionary(doc_clean)


# Creating the term dictionary of our courpus, where every unique term is assigned an index. dictionary = corpora.Dictionary(doc_clean)

# Converting list of documents (corpus) into Document Term Matrix using dictionary prepared above.
doc_term_matrix = [dictionary.doc2bow(doc) for doc in doc_clean]

Lda = gensim.models.ldamodel.LdaModel

# Running and Trainign LDA model on the document term matrix.
ldamodel = Lda(doc_term_matrix, num_topics=3, id2word = dictionary, passes=50)

print(ldamodel.print_topics(num_topics=3, num_words=3))

[(0, '0.065*"driving" + 0.065*"pressure" + 0.064*"stress"'), (1, '0.135*"sugar" + 0.054*"bad" + 0.054*"consume"'), (2, '0.072*"sister" + 0.072*"father" + 0.041*"better"')]


In [9]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = ['Tommorow is my birthday and tomorrow is India semi final. Tomorrow is Friday.',
          'Birthdays are always special.',
          'Data Science is fun to learn.',
          'Birthday party is fun']
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)



print(X.toarray())

[[0 1 0 1 0 0 1 1 0 1 3 0 1 0 0 1 0 0 1 2]
 [1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0 1 0 1 1 0 0 1 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0]]


In [1]:
!python -m spacy download en

  Running setup.py install for en-core-web-sm: started
    Running setup.py install for en-core-web-sm: finished with status 'done'

    Error: Couldn't link model to 'en'
    Creating a symlink in spacy/data failed. Make sure you have the required
    permissions and try re-running the command as admin, or use a
    virtualenv. You can still import the model as a module and call its
    load() method, or create the symlink manually.

    C:\Users\mmarri\AppData\Local\Continuum\anaconda3\lib\site-packages\en_core_web_sm
    -->
    C:\Users\mmarri\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy\data\en


    Creating a shortcut link for 'en' didn't work (maybe you don't have
    admin permissions?), but you can still load the model via its full
    package name: nlp = spacy.load('{name}')
    Download successful but linking failed



You are using pip version 10.0.1, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
